version: '3'
services:
  front:
    container_name: react
    image: wldusdl34/myblogfront:latest
    restart: always
    ports:
    - "8080"
    networks:
      - lns-network

networks:
  lns-network:
    name: myblogall_default